# Generated by Django 2.0.4 on 2018-04-21 07:24

import common.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardedBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded', models.DateTimeField(default=django.utils.timezone.now)),
                ('money_spent', common.fields.MoneyField(decimal_places=2, default=0, max_digits=10)),
                ('amount', common.fields.MoneyField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_type', models.IntegerField(choices=[(1, 'Bonus awarded on login to the application.'), (2, 'Bonus awarded when user deposits money on account.')])),
                ('bonus_amount', common.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField()),
                ('wagering_requirement', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('min_time_between_award', models.DurationField(null=True)),
                ('min_deposit_amount', common.fields.MoneyField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='awardedbonus',
            name='bonus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bonus.Bonus'),
        ),
    ]
