# Generated by Django 2.0.4 on 2018-04-23 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20180423_1933'),
        ('bonus', '0002_awardedbonus_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardedbonus',
            name='awarded_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wallet.Deposit'),
        ),
        migrations.AddField(
            model_name='awardedbonus',
            name='cashed_in',
            field=models.BooleanField(default=False),
        ),
    ]
