# Generated by Django 2.0.4 on 2018-04-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0003_auto_20180423_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awardedbonus',
            name='money_spent',
        ),
        migrations.AddField(
            model_name='bonus',
            name='awards_real_money',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bonus',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
