# Generated by Django 2.0.4 on 2018-04-24 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bonus', '0003_auto_20180423_1933'),
        ('wallet', '0002_auto_20180423_1933'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlayed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won', models.BooleanField(default=False)),
                ('funded_with_bonus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bonus.AwardedBonus')),
                ('funded_with_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wallet.Wallet')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='player.Player')),
            ],
        ),
    ]
