# Generated by Django 2.0.4 on 2018-04-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
